name: NTXA Auto Signer

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'رابط ملف الـ IPA المباشر'
        required: true

jobs:
  sign:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install zsign
        run: brew install zsign

      - name: Download and Sign
        run: |
          curl -L "${{ github.event.inputs.ipa_url }}" -o original.ipa
          zsign -k cert.p12 -p "${{ secrets.P12_PASSWORD }}" -m profile.mobileprovision -o signed_ntxa.ipa original.ipa

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          files: signed_ntxa.ipa
          tag_name: v${{ github.run_number }}
          name: "NTXA Signed Release #${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Install Link
        run: |
          IPA_URL="https://github.com/${{ github.repository }}/releases/download/v${{ github.run_number }}/signed_ntxa.ipa"
          echo "INSTALL_LINK=itms-services://?action=download-manifest&url=https://plist-service.vercel.app/plist?url=$IPA_URL" >> $GITHUB_ENV

      - name: Display Install Link
        run: |
          echo "--------------------------------------------------"
          echo "رابط التثبيت المباشر هو:"
          echo "${{ env.INSTALL_LINK }}"
          echo "--------------------------------------------------"
